# Generated by Django 5.2.3 on 2025-06-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbs/')),
                ('content', models.TextField(help_text='Write in Markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
